<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:apikit="http://www.mulesoft.org/schema/mule/apikit" xmlns:http="http://www.mulesoft.org/schema/mule/http"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/apikit http://www.mulesoft.org/schema/mule/apikit/current/mule-apikit.xsd">

    <apikit:config name="api-config" raml="org/mule/module/apikit/schema/xxe-attack.raml" consoleEnabled="true" consolePath="console"/>

    <flow name="api-main">
        <http:inbound-endpoint host="localhost" port="${serverPort}" path="api"/>
        <apikit:router config-ref="api-config"/>
        <exception-strategy ref="Global_Mapping_Exception_Strategy"/>
    </flow>

    <flow name="post:/test:application/xml:api-config">
        <set-payload value="#[NullPayload.getInstance()]"/>
    </flow>

    <apikit:mapping-exception-strategy name="Global_Mapping_Exception_Strategy">
        <apikit:mapping statusCode="400">
            <apikit:exception value="org.mule.module.apikit.exception.BadRequestException"/>
            <set-payload value="validation exception: #[exception.causeException.message]"/>
        </apikit:mapping>
    </apikit:mapping-exception-strategy>

</mule>
